name: Linters Check

on:
  # if not triggered on PR - trigger manually, that was made to avoid workflow duplication
  push:
  workflow_dispatch:
    paths:
      - '**/*.c'
      - '**/*.h'
      - '**/*.py'
      - '**/*.sh'

jobs:
  linters:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Clang-Format
        run: |
          sudo apt update
          sudo apt install clang-format

      - name: Run Clang-Format
        run: |
            clang-format --version
            git diff --exit-code --name-only | grep -E '\.c$|\.h$' | grep -v '^lib/' | while read file; do
              clang-format -n "$file"
            done

      - name: Fail if clang-format issues are detected
        run: |
          git diff --exit-code --unified=0 --color=always $(git ls-files '*.c' '*.h' | grep -v '^lib/')
